# AUTOGENERATED
from trajectory_evaluation.evaluate import evaluate_run, Dataset
from pathlib import Path
from trajectory_evaluation.plots import square_plot, results_table, line_plot
folder = '/home/zmxj/code/dm-vio/result'

print('Remember that the previous results can change names, when new results are added to the folder '
      'and this file is recreated. It might be better to copy specific lines from this file rather '
      'than importing the whole file.')

# settings=tumvi.yaml Remove test directory from CMakeLists.txt
res0_tumvi_zmxj_part, gtscale_0_tumvi_zmxj_part = evaluate_run(Path(folder) / 'dmvioresult-tumvi-2024-01-28--15-49-26', Dataset.tumvi, 1, '0_tumvi_zmxj_part: output=console_withgui settings=tumvi.yaml Remove test directory from CMakeLists.txt')

#+DIFF  settings=tumvi.yaml chore: Improve code readability and add comments in CoarseInitializer.cpp
res1_tumvi_zmxj_part, gtscale_1_tumvi_zmxj_part = evaluate_run(Path(folder) / 'dmvioresult-tumvi-2024-06-02--17-34-11', Dataset.tumvi, 1, '1_tumvi_zmxj_part: output=console_withgui settings=tumvi.yaml +DIFF chore: Improve code readability and add comments in CoarseInitializer.cpp')
#+DIFF  settings=tumvi.yaml chore: Improve code readability and add comments in CoarseInitializer.cpp
res2_RT_tumvi_zmxj_part, gtscale_2_RT_tumvi_zmxj_part = evaluate_run(Path(folder) / 'dmvioresult-tumvi-RT-2024-06-02--17-48-26', Dataset.tumvi, 1, '2_RT_tumvi_zmxj_part: output=console_quiet_withgui settings=tumvi.yaml +DIFF chore: Improve code readability and add comments in CoarseInitializer.cpp')
#+DIFF  settings=tumvi.yaml chore: Improve code readability and add comments in CoarseInitializer.cpp
res3_tumvi_zmxj_part, gtscale_3_tumvi_zmxj_part = evaluate_run(Path(folder) / 'dmvioresult-tumvi-2024-06-02--17-51-16', Dataset.tumvi, 1, '3_tumvi_zmxj_part: output=console_quiet_withgui settings=tumvi.yaml +DIFF chore: Improve code readability and add comments in CoarseInitializer.cpp')
#+DIFF  settings=tumvi.yaml chore: Improve code readability and add comments in CoarseInitializer.cpp
res4_RT_tumvi_zmxj_part, gtscale_4_RT_tumvi_zmxj_part = evaluate_run(Path(folder) / 'dmvioresult-tumvi-RT-2024-06-02--17-53-19', Dataset.tumvi, 1, '4_RT_tumvi_zmxj_part: output=console_quiet_withgui settings=tumvi.yaml +DIFF chore: Improve code readability and add comments in CoarseInitializer.cpp')
#+DIFF  settings=tumvi.yaml chore: Improve code readability and add comments in CoarseInitializer.cpp
res5_tumvi_zmxj_part, gtscale_5_tumvi_zmxj_part = evaluate_run(Path(folder) / 'dmvioresult-tumvi-2024-06-02--19-11-57', Dataset.tumvi, 1, '5_tumvi_zmxj_part: output=console_quiet_withgui settings=tumvi.yaml +DIFF chore: Improve code readability and add comments in CoarseInitializer.cpp')
